/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views_p;

import Logica.Conexion;
import Logica.Datos;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import com.mysql.jdbc.Statement;
import java.awt.Color;

/**
 *
 * @author MEDWINI
 */
public class PanelDeshabilitar extends javax.swing.JPanel {

    /**
     * Creates new form PanelDeshabilitar
     */
    Conexion Conec = new Conexion();
    Connection cn = Conec.getConexion();
    Datos dtos = new Datos(); //-------------

    public PanelDeshabilitar() {
        initComponents();
        this.ListaProductos.setModel(Conec.Obt_Opciones());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaProductos = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        BtnCancelar = new javax.swing.JButton();
        BtnDeshabilitar = new javax.swing.JButton();
        BtnHabilitar = new javax.swing.JButton();
        BtnActualizar = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(537, 332));
        setMinimumSize(new java.awt.Dimension(537, 332));
        setPreferredSize(new java.awt.Dimension(537, 332));

        jPanel1.setBackground(new java.awt.Color(204, 102, 0));

        ListaProductos.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ListaProductos.setSelectionBackground(new java.awt.Color(255, 204, 0));
        jScrollPane1.setViewportView(ListaProductos);

        jLabel1.setFont(new java.awt.Font("Rockwell Condensed", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 0));
        jLabel1.setText("Seleccione el producto que necesita deshabilitar");

        BtnCancelar.setBackground(new java.awt.Color(255, 204, 0));
        BtnCancelar.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        BtnCancelar.setText("Cancelar");
        BtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarActionPerformed(evt);
            }
        });

        BtnDeshabilitar.setBackground(new java.awt.Color(255, 204, 0));
        BtnDeshabilitar.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        BtnDeshabilitar.setText("Deshabilitar");
        BtnDeshabilitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeshabilitarActionPerformed(evt);
            }
        });

        BtnHabilitar.setBackground(new java.awt.Color(255, 204, 0));
        BtnHabilitar.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        BtnHabilitar.setText("Habilitar");
        BtnHabilitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHabilitarActionPerformed(evt);
            }
        });

        BtnActualizar.setBackground(new java.awt.Color(255, 204, 0));
        BtnActualizar.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        BtnActualizar.setText("Actualizar");
        BtnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BtnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnDeshabilitar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnHabilitar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(84, 84, 84))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(BtnDeshabilitar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnHabilitar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnCancelar)
                    .addComponent(BtnActualizar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_BtnCancelarActionPerformed

    private void BtnDeshabilitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeshabilitarActionPerformed
        // TODO add your handling code here:

        String Prod = "";
        int men = ListaProductos.getSelectedIndex();
        if (men > 0) {
            Prod = ListaProductos.getSelectedValue().toString();
            int Codigo_Prod = Conec.Consultar_Prod(Prod);
            dtos.Cod_Producto = Codigo_Prod;
            PreparedStatement prest;
            try {
                prest = cn.prepareStatement("DELETE FROM Disponibles WHERE Cod_Productos = '" + Codigo_Prod + "'");
                if (prest.executeUpdate() <= 0) {
                    JOptionPane.showMessageDialog(this, "El producto está deshabilitado.", "INFORMACIÓN", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Se deshabilitó el producto correctamente.", "INFORMACIÓN", JOptionPane.INFORMATION_MESSAGE);
                    this.ListaProductos.setModel(Conec.Obt_Opciones());
                }

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Ocurrió un error al intentar habilitar el producto.", "ERROR", JOptionPane.ERROR_MESSAGE);
                Logger.getLogger(PanelDeshabilitar.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "No ha seleccionado algún producto. Por favor, intente de nuevo.", "CONFIGURACION", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_BtnDeshabilitarActionPerformed

    private void BtnHabilitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHabilitarActionPerformed
        // TODO add your handling code here:
        String Prod = "";
        int men = ListaProductos.getSelectedIndex();
        if (men > 0) {
            Prod = ListaProductos.getSelectedValue().toString();
            int Codigo_Prod = Conec.Consultar_Prod(Prod);
            String sql = "SELECT * FROM Productos WHERE Cod_Productos = '" + Codigo_Prod + "'";
            Statement st;

            String[] dts = new String[8];
            PreparedStatement Hab;
            try {
                st = (Statement) cn.createStatement();
                ResultSet result = st.executeQuery(sql);

                while (result.next()) {
                    dts[0] = result.getString(1);
                    dts[1] = result.getString(2);
                    dts[2] = result.getString(3);
                    dts[3] = result.getString(4);
                }
                Hab = cn.prepareStatement("UPDATE Productos SET Habilitado = True WHERE Cod_Productos = " + dts[0] + "");

                PreparedStatement dis;

                dis = cn.prepareStatement("INSERT INTO Disponibles (Cod_Productos, Nombre, Descripcion, Precio_Unitario) VALUES (?,?,?,?)");

                int Cod_Prod = Conec.Consultar_Prod(dtos.Nombre);
                dtos.Cod_Producto = Cod_Prod;

                dis.setInt(1, Integer.parseInt(dts[0]));
                dis.setString(2, dts[1]);
                dis.setString(3, dts[2]);
                dis.setDouble(4, Double.valueOf(dts[3]));

                if (dis.executeUpdate() <= 0) {
                    JOptionPane.showMessageDialog(this, "El producto ya está disponible.", "INFORMACIÓN", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Se habilitó el producto correctamente.", "INFORMACIÓN", JOptionPane.INFORMATION_MESSAGE);
                }

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Ocurrió un error al intentar habilitar el producto.", "ERROR", JOptionPane.ERROR_MESSAGE);
                Logger.getLogger(PanelDeshabilitar.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "No ha seleccionado algún producto. Por favor, intente de nuevo.", "CONFIGURACION", JOptionPane.WARNING_MESSAGE);
        }


    }//GEN-LAST:event_BtnHabilitarActionPerformed

    private void BtnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnActualizarActionPerformed
        // TODO add your handling code here:
        this.ListaProductos.setModel(Conec.Obt_Opciones());
    }//GEN-LAST:event_BtnActualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnActualizar;
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnDeshabilitar;
    private javax.swing.JButton BtnHabilitar;
    private javax.swing.JList ListaProductos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
