/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import Logica.Conexion;
//import gnu.io.*;
import java.io.*;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.sql.Connection;
import java.util.Enumeration;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
//import panamahitek.Arduino.PanamaHitek_Arduino;

/**
 *
 * @author MEDWINI
 */
public class FrmPeso extends javax.swing.JFrame {

    /**
     * Creates new form FrmPeso
     */
    double total = 0;
    double precio = 0;
    double kilos = 0;
    Conexion Conec = new Conexion();
    Connection cn = Conec.getConexion();

    //PanamaHitek_Arduino arduino = new PanamaHitek_Arduino();

    public FrmPeso() {
        initComponents();
        Datos();
        setIconImage(new ImageIcon(getClass().getResource("/images/icono.png")).getImage());
        this.setTitle("Cooperativa Cecosesola Ruiz Pineda - Compra por peso");
        this.setLocationRelativeTo(null);
        this.CBMoneda.setModel(Conec.Obt_OpcionesMoneda());
        deshabilitar();
       /* try {
            arduino.arduinoTX("COM1", 9600);
        } catch (Exception ex) {
            Logger.getLogger(FrmPeso.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BtnVolver = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        TxtNombre = new javax.swing.JTextField();
        TxtPrecioU = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TxtTotal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        BtnPesar = new javax.swing.JButton();
        TxtKilos = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        CBMoneda = new javax.swing.JComboBox();
        BtnCalcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 51));
        jPanel1.setMinimumSize(new java.awt.Dimension(507, 437));
        jPanel1.setPreferredSize(new java.awt.Dimension(507, 437));

        jLabel1.setFont(new java.awt.Font("Rockwell Condensed", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 0));
        jLabel1.setText("Compra por peso");

        BtnVolver.setBackground(new java.awt.Color(204, 102, 0));
        BtnVolver.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        BtnVolver.setText("Volver al menú");
        BtnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVolverActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 204, 0));

        TxtNombre.setEditable(false);
        TxtNombre.setBackground(new java.awt.Color(204, 204, 204));
        TxtNombre.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N

        TxtPrecioU.setBackground(new java.awt.Color(204, 204, 204));
        TxtPrecioU.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        TxtPrecioU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPrecioUActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Nombre:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Precio por kilo:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("¿Cuántos kilos necesita?");

        TxtTotal.setEditable(false);
        TxtTotal.setBackground(new java.awt.Color(204, 204, 204));
        TxtTotal.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        TxtTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TxtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtTotalActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Total a pagar:");

        BtnPesar.setBackground(new java.awt.Color(204, 102, 0));
        BtnPesar.setFont(new java.awt.Font("Rockwell Condensed", 1, 24)); // NOI18N
        BtnPesar.setText("PESAR");
        BtnPesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPesarActionPerformed(evt);
            }
        });

        TxtKilos.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        TxtKilos.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Moneda de Pago:");

        CBMoneda.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        CBMoneda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBMonedaActionPerformed(evt);
            }
        });

        BtnCalcular.setBackground(new java.awt.Color(0, 102, 0));
        BtnCalcular.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        BtnCalcular.setForeground(new java.awt.Color(255, 255, 255));
        BtnCalcular.setText("Calcular");
        BtnCalcular.setBorder(null);
        BtnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BtnPesar, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(BtnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TxtPrecioU)
                            .addComponent(TxtNombre)
                            .addComponent(TxtTotal, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TxtKilos)
                            .addComponent(CBMoneda, 0, 250, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CBMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TxtPrecioU)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TxtKilos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnCalcular, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(TxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(BtnPesar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(BtnVolver)
                .addGap(59, 59, 59)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVolverActionPerformed
        // TODO add your handling code here:
        FrmSelect MiSelect = new FrmSelect();
        MiSelect.setVisible(true);
        MiSelect.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setVisible(false);
    }//GEN-LAST:event_BtnVolverActionPerformed

    private void TxtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtTotalActionPerformed

    private void TxtPrecioUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPrecioUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrecioUActionPerformed

    private void BtnPesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPesarActionPerformed
        // TODO add your handling code here: 

        if (TxtTotal.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Por favor, genere el total de la venta.", "SISTEMA DE PESAJE", JOptionPane.WARNING_MESSAGE);
        } else {
            kilos = Double.parseDouble(TxtKilos.getText());
            kilos = kilos * 1000;
            int T_kilos = (int) kilos;
            /*try {
                arduino.sendData("" + T_kilos + "");
                JOptionPane.showMessageDialog(this, "La información ha sido enviada con exito.", "SISTEMA DE PESAJE", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Existe información en el puerto que aún no se ha utilizado.", "SISTEMA DE PESAJE", JOptionPane.WARNING_MESSAGE);
            }*/
        }

    }//GEN-LAST:event_BtnPesarActionPerformed

    private void BtnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCalcularActionPerformed
        // TODO add your handling code here:
        if (CBMoneda.getSelectedItem() == "Seleccione el tipo de moneda que utilizará...") {
            JOptionPane.showMessageDialog(this, "No ha seleccionado la moneda de pago. Por favor, intente de nuevo.", "CONFIGURACION", JOptionPane.WARNING_MESSAGE);
        } else {
            String Moneda = CBMoneda.getSelectedItem().toString();
            String simbolo = Conec.Consult_Moneda(Moneda);
            TxtTotal.setText(simbolo + " " + Pago());
        }

    }//GEN-LAST:event_BtnCalcularActionPerformed

    private void CBMonedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBMonedaActionPerformed
        // TODO add your handling code here:
        String Moneda = CBMoneda.getSelectedItem().toString();
        String simbolo = Conec.Consult_Moneda(Moneda);
        TxtPrecioU.setText("" + simbolo + " " + PrecioFinal() + "");
    }//GEN-LAST:event_CBMonedaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPeso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPeso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPeso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPeso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPeso().setVisible(true);
            }
        });
    }

    public void deshabilitar() {
        TxtNombre.setEditable(false);
        TxtPrecioU.setEditable(false);
        TxtTotal.setEditable(false);
    }

    public double Pago() {
        precio = PrecioFinal();
        kilos = Double.valueOf(TxtKilos.getText());
        total = precio * kilos;
        return total;
    }

    public double PrecioFinal() {
        double PrecioSubF = 0;
        String Moneda = CBMoneda.getSelectedItem().toString();
        double tasa = Conec.Consult_Valor(Moneda);
        PrecioSubF = FrmSelect.PrecioU_Prod / tasa;
        System.out.print(PrecioSubF);
        BigDecimal bd = new BigDecimal(PrecioSubF).setScale(2, RoundingMode.HALF_UP);
        double PrecioFinal = bd.doubleValue();
        return PrecioFinal;
    }

    public void Datos() {
        TxtNombre.setText(FrmSelect.Nombre_Prod);
        TxtPrecioU.setText("Bs. " + FrmSelect.PrecioU_Prod + "");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCalcular;
    private javax.swing.JButton BtnPesar;
    private javax.swing.JButton BtnVolver;
    private javax.swing.JComboBox CBMoneda;
    private javax.swing.JTextField TxtKilos;
    private javax.swing.JTextField TxtNombre;
    private javax.swing.JTextField TxtPrecioU;
    private javax.swing.JTextField TxtTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
